# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Flag files used by cPanel &amp; WHM &trade;
email: kenneth.power@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A comprehensive and growing list of configuration files used
  by cPanel &amp; WHM.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://flagfile.com" # the base hostname & protocol for your site
twitter_username: kennethpower
github_username:  escherlat

# Build settings
markdown: kramdown

timezone: America/Chicago
google_id: UA-71900628-1

disqus_shortname: flagfilecom
